services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  worker:
    build: .
    env_file:
      - .env
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
